flask_application_work_/app.py
from flask import Flask, render_template     #importing flask. -These are some properties that is a class and some methods from the flask libarary that we are going to need
from views import my_view    #importing local imports

app = Flask(__name__)                                   #Making a version of flask
app.register_blueprint(my_view)


@app.errorhandler(404)
def page_not_found(e):
    return render_template("404.html", e=e)



if __name__ == "__main__":                              #__main__ is the name of the global space
    app.run(debug=True, port=8000)                      #These codes are going to handle the running of our application

flask_application_work_/views.py
from flask import render_template, redirect, Blueprint, request

from favourites import fave_bands, add_to_list, del_from_list           #imported a local object from a local file

my_view = Blueprint('my_view', __name__)

# @my_view.route("/")
# def home():
#     return "<h1>Hello World</h1>"


@my_view.route("/")                             
def home():
    return render_template("index.html")

@my_view.route("/Page 1")                           # When the url is our_app/page1
def page1():
    return render_template("page1.html")

@my_view.route("/page2")                            # When the url is our_app/page2    
def page2():
    return render_template("page2.html")

@my_view.route("/page3")                            # When the url is our_app/page3
def page3():
    return render_template("page3.html")

@my_view.route("/page4")                            # When the url is our_app/page4
def page4():
    return render_template("page4.html")

@my_view.route("/page5")                            # When the url is our_app/page5
def page5():
    return render_template("page5.html")

@my_view.route("/admin")                            # When the url is our_app/admin
def admin():
    return render_template("admin.html")

# @my_view.route("/404")
# def 404():
#     return render_template("404.html", e=e)










# @my_view.route("/about", methods=["GET", "POST"])
# def about():
#     if request.method == "POST":
#         #Another bit of logic to determine add from remove
#         if not new_band:
#             old_band = request.form["band.entry"]
#             del_from_list(old_band)
#         new_band = request.form["add_band"]
#         add_to_list(new_band)
#         #Then I need to pass that input back to my favourite files
#     return render_template("about.html", bands=fave_bands)

flask_application_work_/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>This is the about me page</h1>

<!-- <h3>These are my favourite artists:</h3>
<p>{{ bands }}</p>
{% for each_band in bands %}
<h1>{{ each_band }}</h1>
{% endfor %} -->
<form action="/about" method="POST">
{% if "Spice Girls" in bands %}
<h1>{{ bands[0] }}</h1>
{% else %}
{% for x in bands %}
<h3 name="band_entry">{{ x }}</h3><button type="submit" name="delete_btn">(delete!)</button>
{% endfor %}
{% endif %}
</form>



<form action="/about" method="post">
    <input type="text" name="add_band" id="band_add" placeholder="Enter the band you wish to add!">
    <button> type="submit" style="display: none;">Submit</button>
</form>


{% endblock %}

flask_application_work_/templates/admin.html
{% extends 'base.html' %}

{% block content %}
<h1>Admin</h1>
{% endblock %}

flask_application_work_/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{{url_for('static',filename='main.css')}}">
    <script src="{{url_for('static',filename='app.js')}}"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JavaScript Events</title>
</head>
<body onload="checkCookies()">
    <nav>
        <a href="{{ url_for('my_view.home') }}"><li>Home</li></a>
        <a href="{{ url_for('my_view.page1') }}"><li>Page 1</li></a>
        <a href="{{ url_for('my_view.page2') }}"><li>Page 2</li></a>
        <a href="{{ url_for('my_view.page3') }}"><li>Page 3</li></a>
        <a href="{{ url_for('my_view.page4') }}"><li>Page 4</li></a>
        <a href="{{ url_for('my_view.page5') }}"><li>Page 5</li></a>
        <a href="{{ url_for('my_view.admin') }}"><li>Admin</li></a>
        <a href="{{ url_for('my_view.404') }}"><li>404</li></a>
    </nav>
    <header>
        This is the custom header
    </header>

    {% block content %}

    {% endblock %}

    <!-- <footer>This is the custom footer</footer>
    <aside>This has extended from base</aside> -->
    
</body>
</html>

flask_application_work_/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>This is the main page</h1>
<p>custom homepage content</p>
{% endblock %}

flask_application_work_/templates/index.html
{% extends 'base.html' %}

{% block content %}

<body onload="checkCookies()">
    <div class="flex-container-h">
    <div>
    <h1>JavaScript Events</h1>
    <div class="flex-container-h">
        <button>Dark Mode</button>
    </div>
    <h2>Innovate Coding</h2>
    <p id="intro-text">This is an inte∆ractive website for demonstrating a selection of events in JavaScript.</p>

    <br>

    <div class="main-box">
    <h3 class="main-title">onclick Events</h3>
    <p class="main-text">This is an event that occurs as a result of the user 'clicking' a specific element.</p>
    <p onclick="changeText(this)" class="example-text">click this text to change it</p>
    <div class="flex-container-h2">
    <button onclick="displayDate(date)" class="example-button">Display Date</button>
    <p class="example-text" id="date"></p>
    </div>
    </div>

    <br>
    <br>

    <div class="main-box">
    <h3 class="main-title">onload Events</h3>
    <p class="main-text">This is an event that occurs as soon as the user has loaded the web page.</p>
    <p class="example-text" id="cookie"></p>
    </div>

    <br>
    <br>

    <div class="main-box">
    <h3 class="main-title">Mouse Events</h3>
    <p class="main-text">This is an event that occurs when the user moves their cursor over a specific element.</p>
    <div class="flex-container-h3">
        <div onmouseover="mOver(this)" onmouseout="mOut(this)" class="colour-box example-text">
        </div>
        <div onmouseover="mOver(this)" onmouseout="mOut(this)" class="colour-box example-text">
        </div>
        <div onmouseover="mOver(this)" onmouseout="mOut(this)" class="colour-box example-text">
        </div>
    </div>
    </div>

    <br>
    <br>

    <div class="main-box">
    <h3 class="main-title">Extra:</h3>
        <p class="main-text">Additional features that can be used in developing a website with JavaScript.</p>
        <h4 class="main-text">Alert</h4>

        <p class="main-text">An alert is used to notify the user via a pop-up window.</p>
        <button onclick="sendAlert()" class="example-button">Display Host Name</button>
        <h4 class="main-text">Toggle</h4>
        <p class="main-text">TBC</p>
    </div>

    <br>
    <br>

    </div>
    </div>
    {% endblock %}

flask_application_work_/templates/page1.html
{% extends 'base.html' %}

{% block content %}
<h1>Page 1</h1>
{% endblock %}

flask_application_work_/templates/page2.html
{% extends 'base.html' %}

{% block content %}
<h1>Page 2</h1>
{% endblock %}

flask_application_work_/templates/page3.html
{% extends 'base.html' %}

{% block content %}
<h1>Page 3</h1>
{% endblock %}

flask_application_work_/templates/page4.html
{% extends 'base.html' %}

{% block content %}
<h1>Page 4</h1>
{% endblock %}

flask_application_work_/templates/page5.html
{% extends 'base.html' %}

{% block content %}
<h1>Page 5</h1>
{% endblock %}